[versions]
mockk = "1.14.6"
kotlin = "2.2.21"
ksp = "2.2.21-2.0.4"
lifecycle = "2.10.0"
navigation = "2.9.6"
systemUiController = "0.36.0"
junit = "1.3.0"
espresso = "3.7.0"
androidCore = "1.17.0"
activityCompose = "1.12.0"
viewModel = "2.10.0"
dagger = "2.57.2"
coroutines = "1.10.2"
junit4 = "4.13.2"
testng = "7.11.0"
mockkJvm = "1.14.6"
instrumentalTest = "1.7.0"
testRunner = "1.7.0"
coil = "2.7.0"
dataStore = "1.2.0"
room = "2.8.4"
appCompat = "1.7.1"
adMob = "24.8.0"
media3 = "1.8.0"
cameraX = "1.5.1"
materialDialogs = "0.9.0"
kotlinSerialization = "1.9.0"
kotlinSerializationPlugin = "2.2.0"
immutableCollection = "0.4.0"
firebaseBom = "34.6.0"
firebaseCrashlyticsGradle = "2.9.5"
googleServices = "4.4.4"
firebaseCrashlyticsPlugin = "3.0.6"
androidGradlePlugin = "8.13.1"
versionKotlinSerialization = "2.2.21"
compileSdk = "36"
minSdk = "26"
minifyEnabledRelease = "true"
minifyEnabledDebug = "false"
javaCompatibilityVersion = "VERSION_17"
jvmTarget = "17"
packageName = "com.xxmrk888ytxx.backgroundvideovoicerecord"
composePlugin = "2.2.21"
material = "1.13.0"
workManager = "2.11.0"
documentFile = "1.1.0"


[libraries]
# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version = "2025.11.01" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
compose-system-ui-controller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "systemUiController" }

# TestAndroid
test-android-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
test-android-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
test-android-mockk = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
test-android-mockk-agent = { group = "io.mockk", name = "mockk-agent", version.ref = "mockk" }

# AndroidX
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidCore" }
androidx-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "viewModel" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

# ViewModel
viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "viewModel" }
viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "viewModel" }

# Dagger
dagger-core = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }

# Coroutines
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }

# DocumentFile
document-file = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentFile" }

# Test
test-junit = { group = "junit", name = "junit", version.ref = "junit4" }
test-mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
test-testng = { group = "org.testng", name = "testng", version.ref = "testng" }
test-mockk-jvm-agent = { group = "io.mockk", name = "mockk-agent-jvm", version.ref = "mockkJvm" }

# InstrumentalTest
instrumental-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
instrumental-test-runner = { group = "androidx.test", name = "runner", version.ref = "testRunner" }
instrumental-test-core = { group = "androidx.test", name = "core", version.ref = "instrumentalTest" }
instrumental-test-junit = { group = "androidx.test.ext", name = "junit-ktx", version = "1.1.4" }
instrumental-test-rules = { group = "androidx.test", name = "rules", version.ref = "instrumentalTest" }

# Coil
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

# DataStore
datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStore" }

# Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-test = { group = "androidx.room", name = "room-testing", version.ref = "room" }

# AppCompat
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompat" }
appcompat-resources = { group = "androidx.appcompat", name = "appcompat-resources", version.ref = "appCompat" }

# Media3
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }

# CameraX
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraX" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraX" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraX" }
camera-video = { group = "androidx.camera", name = "camera-video", version.ref = "cameraX" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraX" }
camera-extensions = { group = "androidx.camera", name = "camera-extensions", version.ref = "cameraX" }

# MaterialDialog
material-dialogs = { group = "io.github.vanpra.compose-material-dialogs", name = "datetime", version.ref = "materialDialogs" }

# KotlinSerialization
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerialization" }

# ImmutableCollection
immutable-collections = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "immutableCollection" }

# Firebase
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx", version = "19.4.4" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx", version = "22.5.0" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# WorkManager
workmanager = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "versionKotlinSerialization" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "composePlugin" }
room = { id = "androidx.room", version.ref = "room" }
